# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-15 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='banner',
            table='s_banner',
        ),
        migrations.AlterModelTable(
            name='goods',
            table='s_goods',
        ),
        migrations.AlterModelTable(
            name='goodscategory',
            table='s_category',
        ),
        migrations.AlterModelTable(
            name='goodsimage',
            table='s_goods_image',
        ),
        migrations.AlterModelTable(
            name='hotsearchwords',
            table='s_host_search_words',
        ),
        migrations.AlterModelTable(
            name='indexad',
            table='s_index_ad',
        ),
    ]
