# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-15 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190115_1707'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goodscategorybrand',
            table='s_brand',
        ),
    ]
