# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-15 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0002_auto_20190115_1544'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useraddress',
            table='s_address',
        ),
        migrations.AlterModelTable(
            name='userfav',
            table='s_user_fav',
        ),
        migrations.AlterModelTable(
            name='userleavingmessage',
            table='s_messages',
        ),
    ]
